http:
  routers:
    dsm:
      entryPoints:
        - websecure
      rule: "Host(`{{env "DSM_EXTERNAL_DOMAIN"}}`)"
      service: dsm
    dsm-old:
      entryPoints:
        - websecure
      rule: "Host(`data.andrewmiller.xyz`)"
      service: dsm-old
    homeassistant:
      entryPoints:
        - websecure
      rule: "Host(`homeassistant.andrewmiller.dev`)"
      service: homeassistant
    router:
      entryPoints:
        - websecure
      rule: "Host(`router.andrewmiller.dev`)"
      service: router
  services:
    dsm:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "{{env "DSM_INTERNAL_URL"}}"
    dsm-old:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "https://192.168.1.20:8443"
    homeassistant:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "http://192.168.1.30:8123"
    router:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "https://192.168.1.1:8443"
